### PR TITLE
Skipped timing-out deployed server test

### PR DESCRIPTION
**Pull request by luuuk**

### CODE REVIEW

**Review by mackenzieleach — CHANGES_REQUESTED** [review]
It looks like the deployment to Heroku failed in the actions and I'm assuming this is not the behavior you were expecting. It looks like it threw and error message about us being out build minutes on Heroku! We may want to fix that before merging this in to make sure it deploys.

**Comment by luuuk** [comment]
> It looks like the deployment to Heroku failed in the actions and I'm assuming this is not the behavior you were expecting. It looks like it threw and error message about us being out build minutes on Heroku! We may want to fix that before merging this in to make sure it deploys.

@mackenzieleach I saw the failure - I believe on merge into main, the deployment should work though

**Comment by luuuk** [comment]
Didnt mean to close oops

**Review by mackenzieleach — APPROVED** [review]
We can always revert if for some reason it doesn't but I couldn't remember exactly how Heroku worked with a PR!

**Pull request merged**
